sudo: false
language: go
go:
- 1.10
- 1.11
- 1.12
- 1.13
- tip
go_import_path: github.com/Shopify/go-storage

env:
    - DEP_VERSION="0.5.4"
before_install:
    - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
    - chmod +x $GOPATH/bin/dep
install:
    - dep ensure
