name: go-storage

up:
  - go:
      version: "1.21.6"
      modules: true
  - custom:
        name: Load dependencies
        met?: go mod tidy
        meet: go mod tidy

commands:
  test: go test -race ./...
  lint:
    run: bin/golangci-lint run
    desc: Static verification using golangci or autofix issues when possible.
    syntax:
      optional: --fix
