name: CI

on:
  push:
    tags:
    - v*
    branches:
    - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: v1.56.2

  mod-tidy:
    name: Go Mod Tidy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup go
      uses: actions/setup-go@v5.0.1
      with:
        go-version: 1.21.x

    - name: Cache
      uses: actions/cache@v4.0.2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Tidy
      run: |
        cp go.sum go.sum.old
        go mod tidy
        diff go.sum.old go.sum

  test:
    name: Go ${{ matrix.go-version }} test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version:
        - 1.21.x

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup go
      uses: actions/setup-go@v5.0.1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Cache
      uses: actions/cache@v4.0.2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Test
      run: go test -v -race ./...
